name: chess
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  flutter_svg:
  bloc:
  flutter_bloc:
  equatable:
  url_launcher:
  font_awesome_flutter:
  webview_flutter:
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bishop_black.svg
    - lib/assets/bishop_white.svg
    - lib/assets/king_black.svg
    - lib/assets/king_white.svg
    - lib/assets/knight_black.svg
    - lib/assets/knight_white.svg
    - lib/assets/pawn_black.svg
    - lib/assets/pawn_white.svg
    - lib/assets/queen_black.svg
    - lib/assets/queen_white.svg
    - lib/assets/rook_black.svg
    - lib/assets/rook_white.svg
    - lib/assets/king_bg.png
    - lib/assets/anuj.jpg
    - lib/assets/draw-button.svg
    - lib/assets/resign.svg
    - lib/assets/forward-button.svg
    - lib/assets/back-button.svg
    - lib/assets/lottie/win_animation.json
    - lib/assets/lottie/draw.json
